// <auto-generated />
using DatabasePostgresSQLEFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabasePostgresSQLEFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabasePostgresSQLEFCore.Models.People", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("people", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DatabasePostgresSQLEFCore.Models.PeopleLegal", b =>
                {
                    b.HasBaseType("DatabasePostgresSQLEFCore.Models.People");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("people_legal", (string)null);
                });

            modelBuilder.Entity("DatabasePostgresSQLEFCore.Models.PeoplePhysical", b =>
                {
                    b.HasBaseType("DatabasePostgresSQLEFCore.Models.People");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("people_physical", (string)null);
                });

            modelBuilder.Entity("DatabasePostgresSQLEFCore.Models.PeopleLegal", b =>
                {
                    b.HasOne("DatabasePostgresSQLEFCore.Models.People", null)
                        .WithOne()
                        .HasForeignKey("DatabasePostgresSQLEFCore.Models.PeopleLegal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabasePostgresSQLEFCore.Models.PeoplePhysical", b =>
                {
                    b.HasOne("DatabasePostgresSQLEFCore.Models.People", null)
                        .WithOne()
                        .HasForeignKey("DatabasePostgresSQLEFCore.Models.PeoplePhysical", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
